name               'kernel-modules'
maintainer         'Criteo'
maintainer_email   'sre-core@criteo.com'
license            'all_rights'
description        'Manage kernel modules on linux'
long_description   IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url         'https://github.com/criteo-cookbooks/kernel-modules.git'
source_url         'https://github.com/criteo-cookbooks/kernel-modules.git'
version            '0.1.0'
supports 'debian'
supports 'rhel'
supports 'centos'
