name 'kernel-modules'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kernel-modules'
long_description 'Installs/Configures kernel-modules'
version '0.1.0'
